apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-showcase
  annotations:
    github.com/project-slug: its-mitesh-kumar/backstage-showcase
spec:
  type: other
  lifecycle: unknown
  owner: user:development/guest
